Environment Variables:
  LANGUAGE: "en"
  SUPPORTED_LANGUAGES: "en"
  EVE_PUBLIC_DATABASE_FILE: "_publicData/public.db"
  EVE_PRIVATE_DATABASE_FOLDER: "_privateData/"
  AUTH_DATA_FOLDER: "auth/.gitignore/"
  SDE_PATH: "_sde/"
  SYSTEM_GRAPH_FILE: "route/.gitignore/eve_graph.json"
